Repository cleverage/daltons, pull requests merged in 2022-04, with the labels that each got.

#376 Move CI from Travis to GitHub actions
  .github/workflows/tests.yml
  __tests__/integration/__snapshots__/examples.js.snap
  __tests__/integration/examples.js
Labels: enhancement

#379 Remove Travis conf
  .travis.yml
  package-lock.json
Labels: automerge

#380 Upgrade dependencies
  __tests__/integration/examples.js
  package-lock.json
  src/browse.js
  src/cli.js
  src/getStats.js
  src/index.js
Labels: automerge

#392 Move to current LTS version of Node: 16
  .github/workflows/tests.yml
  .nvmrc
Labels: automerge

#210 Added computation of best perfectWidth with kmeans algo
  package-lock.json
  package.json
  src/index.js
Labels: enhancement

#393 Upgrade Puppeteer
  package-lock.json
  package.json
Labels: dependencies, automerge

#397 Rework the target widths computing algorithm
  __tests__/integration/__snapshots__/examples.js.snap
  __tests__/integration/examples.js
  examples/simple/configuration.js
  package-lock.json
  package.json
  src/cli.js
  src/index.js
Labels: enhancement, high priority

#401 Dependencies upgrades + presentation improvements
  __tests__/integration/examples.js
  examples/nicolas-hoizey.com/run.sh
  examples/simple/run.sh
  package-lock.json
  package.json
  src/adjustViewportsWithStats.js
  src/getStats.js
  src/index.js
Labels: enhancement
